name: Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # 이 줄이 5분마다 실행을 설정합니다.

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py requests beautifulsoup4

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python discord_bot.py

      - name: Commit and Push content list
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --global user.email "pgj127@gmail.com"
          git config --global user.name "PGjun"
          git add content_list.txt
          git commit -m "Update content list" -a || echo "No changes to commit"
          git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
