name: Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # 최신 버전으로 변경

      - name: Set up Python
        uses: actions/setup-python@v3 # 최신 버전으로 변경
        with:
          python-version: '3.12.2' # 파이썬 버전을 3.12.2로 변경

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py requests beautifulsoup4 asyncio

      - name: Run notifier
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python discord_bot.py
